# Generated by Django 5.0.6 on 2024-06-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omboli', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Omboli_Room',
        ),
    ]
